services:
  local_service_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_app_development
      MYSQL_PASSWORD: your_password
    ports:
      - "3307:3306"
  local_service:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - local_service_db
    links:
      - local_service_db
    environment:
      DB_USER: root
      DB_NAME: your_app_development
      DB_PASSWORD: your_password
      DB_HOST: local_service_db
      DB_PORT: "3306"
