default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root 
  password: your_password
  host: mysql-server              
  port: 3306              

development:
  <<: *default
  database: your_app_development

test:
  <<: *default
  database: your_app_test

  




